project:
  name: cocos-snake-fe
  team: games
  type: fe
  repo_path: https://git.garena.com/shopee/shopee-id/showcase-fe/cocos-snake-fe

domain:
  path: /cocos-snake-fe
  prefix: play

dependencies:
  micro_fe: false
  pubsub: false
  gcs: false
